# This is how many blocks up and down the terrain height can vary typically.
height-variance: 5

# The larger this number, the more gradual and gentle the terrain will be
noise-scale: 64

# This is roughly how many blocks tall the chunks are. In Vanilla Minecraft, sea level is 64. Here, the default is 60 blocks. So with a height variance of 5, you can expect the terrain to be in the 56 blocks to 64 blocks tall range.
depth: 60

# Set this to false to disable crater generation
craters: true

# Set this to false to disable flag generation
flags: true